import {Link} from 'react-router-dom';
import {Compass,Car,MapPin,Mountain,Landmark,Ship,Route,Users} from 'lucide-react';
import Hero from '../components/Hero';
import Scene from '../components/Scene';
import {TourCard,Button,Confidence,LocationBlock} from '../components/Shared';
import {GuideCard} from './Guides';
import {tourBySlug} from '../data/tours';
import {destinationBySlug} from '../data/destinations';
import {guides} from '../data/guides';
const categories=[[Route,'Scenic drives','/cape-breton-tours/?category=Scenic+drives'],[Landmark,'History & culture','/cape-breton-tours/?category=History+%26+culture'],[Mountain,'Outdoor adventures','/cape-breton-tours/?category=Nature+%26+outdoors'],[Ship,'Shore excursions','/cape-breton-shore-excursions/'],[Users,'Private tours','/private-cape-breton-tours/'],[Car,'Taxi & transfers','/taxi-sydney-nova-scotia/']];
const faqs=[['Where do your Cape Breton tours start?','Tours start in Sydney, Nova Scotia. We pick up from hotels, private accommodation, the Sydney cruise terminal or another agreed address in the Sydney area.'],['How do I book an experience?','Choose a tour and share your preferred date, group size and pickup location. We’ll discuss availability and a personalised quote. Your booking is confirmed directly with our team.'],['Can I customise my trip?','Yes. Tell us your interests, must-see places and available time. We’ll help you plan a practical route at your pace.'],['Can you pick us up at the cruise terminal?','Cruise pickup can be arranged. Share your ship name and arrival and all-aboard times so we can plan an appropriate route and return-to-ship timing.'],['Do you offer taxi and airport transfers?','Yes. We provide taxi and private transportation in Sydney and across Cape Breton, including transfers to and from Sydney airport (YQY).'],['Are admission tickets included?','Inclusions, admission fees and any extra costs are confirmed with your quote before booking.']];
export default function Home(){return <><Hero/>
<section className="market-benefits wrap" aria-label="Why travel with us">{[[Compass,'Local Cape Breton operator','Based in Sydney, Nova Scotia.'],[Users,'Private tours','Just your group, at your own pace.'],[Ship,'Cruise terminal pickup','Shore excursions around your ship’s schedule.'],[MapPin,'Flexible itineraries','Your stops, your timing, planned with you.']].map(([Icon,title,text])=><div key={title}><Icon size={27}/><div><h2>{title}</h2><p>{text}</p></div></div>)}</section>
<section className="market-section wrap"><div className="market-heading"><div><h2>Popular Cape Breton tours</h2><p>Private sightseeing from Sydney, from the <Link to="/cabot-trail-tours/">Cabot Trail</Link> to the <Link to="/fortress-of-louisbourg-tour/">Fortress of Louisbourg</Link>.</p></div><Link to="/cape-breton-tours/">See all tours</Link></div><div className="tour-grid home-experiences">{['cabot-trail','fortress-of-louisbourg','skyline-trail','highland-village'].map(slug=><TourCard key={slug} tour={tourBySlug(slug)}/>)}</div></section>
<section className="market-section wrap"><div className="market-heading"><div><h2>What’s your kind of adventure?</h2><p>There’s more than one way to fall in love with Cape Breton.</p></div></div><div className="category-grid">{categories.map(([Icon,label,url])=><Link key={label} to={url}><Icon size={28} strokeWidth={1.6}/><span>{label}</span></Link>)}</div></section>
<section className="market-promo wrap"><div><span className="promo-kicker">YOUR DAY. YOUR WAY.</span><h2>A little less planning.<br/>A lot more exploring.</h2><p>Tell us how much time you have and what you’d like to see. We’ll help create a private Cape Breton sightseeing itinerary covering places such as the Cabot Trail, Fortress of Louisbourg, Highland Village and the Cape Breton Highlands.</p><Button to="/private-cape-breton-tours/">Plan a private tour</Button></div><div className="promo-visual"><Scene name="autumn" decorative/><span>Scenic illustration</span></div></section>
<section className="shore-market wrap"><div className="shore-icon"><Ship size={44}/></div><div><span className="promo-kicker">ARRIVING IN SYDNEY BY CRUISE SHIP?</span><h2>Private shore excursions, planned around your ship.</h2><p>Pickup at the Sydney cruise terminal, Louisbourg, Cabot Trail and Bras d’Or Lake options, and return-to-ship timing planned from your all-aboard time.</p></div><Button to="/sydney-cruise-port-tours/">Explore cruise excursions</Button></section>
<section className="market-section wrap"><div className="market-heading"><div><h2>Places that deserve a spot on your list</h2><p>Get to know Cape Breton’s best-loved destinations before you go.</p></div><Link to="/destinations/">All destinations</Link></div><div className="destination-row">{['cabot-trail','fortress-of-louisbourg','iona','cape-breton-highlands'].map(destinationBySlug).map(d=><Link className="destination-card" key={d.slug} to={d.path}><Scene name={d.image} sizes="(max-width: 760px) 50vw, 25vw" decorative/><div><h3>{d.name}</h3><p>{d.tagline}</p></div><small>Illustration</small></Link>)}</div></section>
<Confidence/>
<section className="market-section wrap"><div className="market-heading"><div><h2>Cape Breton travel guides</h2><p>Practical local advice for planning your days on the island.</p></div><Link to="/guides/">All guides</Link></div><div className="guide-grid">{guides.map(g=><GuideCard key={g.slug} guide={g}/>)}</div></section>
<section className="market-section wrap"><div className="market-heading"><div><h2>Good to know before you go</h2><p>A few answers to help get your plans moving.</p></div></div><div className="home-faq">{faqs.map(([q,a])=><details className="faq" key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></section>
<LocationBlock/>
<section className="market-ending"><div className="wrap"><Compass size={35}/><h2>Your next great day is out there.</h2><p>Tell us your dates and ideas, and we’ll reply with a plan and a quote.</p><Button to="/book/">Get a quote</Button></div></section></>}
