import Scene from '../components/Scene';
import {Link} from 'react-router-dom';
import {Phone,MessageCircle,ArrowUpRight} from 'lucide-react';
import {PageHero,Title,Services,Button,CTA,LocationBlock,TrustStrip} from '../components/Shared';
import {whatsapp,business} from '../data/tours';
import Booking from './Booking';
export function Taxi(){return <><PageHero eyebrow="TAXI & PRIVATE TRANSPORTATION" title={<>Everyday rides.<br/><em>Extraordinary care.</em></>} text="Airport arrivals, local journeys and a comfortable ride to your next adventure." image="coast"/><section className="wrap section"><div className="heading-row"><Title eyebrow="ACROSS CAPE BRETON">Where you need to be.<br/><em>How you want to travel.</em></Title><p className="heading-copy">Share your pickup, destination, group size and timing. We’ll confirm availability and a quote for your journey.</p></div><Services all/><div className="ride-call"><div><h3>Need a ride?</h3><p>Talk directly with us to arrange your pickup.</p></div><a className="button navy" href="tel:+19025494542"><Phone size={18}/>{business.phone}</a><a className="text-link" href={whatsapp()} target="_blank" rel="noreferrer">Enquire on WhatsApp <MessageCircle size={18}/></a></div><div className="vehicle-feature"><img loading="lazy" src="/images/vehicle.webp" alt="Supplied promotional illustration of the tour and taxi service"/><div><h3>Settle in.<br/>Enjoy the ride.</h3><p>Tell us about luggage, child seats, mobility requirements and your party size. We’ll confirm suitable vehicle arrangements before booking.</p><p className="fine-print">Promotional vehicle illustration. Actual vehicle and capacity are confirmed directly.</p><Button to="/book?service=Taxi%20Service">Request transportation</Button></div></div></section><CTA/></>}
export function About(){return <><PageHero eyebrow="OUR STORY" title={<>Local journeys.<br/><em>Lasting memories.</em></>} text="A warm welcome to the island we call home."/><section className="wrap section about-story"><div><Title eyebrow="NEW SCOTLAND COASTAL & CAPE BRETON TOURS">An island best seen<br/><em>at your own pace.</em></Title><p className="lead">Some of the best moments happen between destinations. A bend in the road. A harbour in the evening light. A view that makes you ask for one more stop.</p><p>We help visitors experience Cape Breton through personalised scenic tours and comfortable transportation. From a simple airport pickup to a carefully planned day exploring, our approach starts with listening to what you need.</p><p>Based in Sydney, Nova Scotia, we bring tours and everyday travel together. You can plan directly with us, ask questions and shape a journey that fits your time on the island.</p><Button to="/contact">Let’s get to know your plans</Button></div><figure><Scene name="harbour"/><figcaption>Maritime travel inspiration · supplied illustration</figcaption></figure></section><TrustStrip/><section className="wrap section"><div className="values-grid">{[['Our approach','A good journey starts with a conversation. Your interests, pace and practical needs guide the plan.'],['Comfort & hospitality','From the first enquiry to the day you travel, we aim to make the arrangements clear and personal.'],['Our vehicles','Vehicle details, passenger capacity, luggage and accessibility arrangements are confirmed for your specific journey.']].map(([t,p])=><div key={t}><h3>{t}</h3><p>{p}</p></div>)}</div></section><CTA/></>}
export function Contact(){return <><PageHero eyebrow="GET IN TOUCH" title={<>Let’s plan<br/><em>your journey.</em></>} text="A question, a wish list, or just a starting point. We’d love to hear from you."/><LocationBlock/><Booking/></>}
export function Legal({privacy=false}){return <section className="wrap section legal"><Title as="h1" eyebrow="HELPFUL INFORMATION">{privacy?'Privacy & your enquiry':'Before you book'}</Title>{privacy?<><h3>What you share</h3><p>The enquiry form uses the details you enter to prepare a message. This website does not submit your enquiry to a booking database. When you choose WhatsApp or email, you send your details through that service.</p><h3>Third-party services</h3><p>Google Maps, Google Fonts, WhatsApp and your email provider may process information under their own privacy policies. Saved tours are stored only in your browser so you can revisit your wish list. This website does not use advertising or analytics cookies.</p><h3>Contact us</h3><p>For questions about information you send to the business, email <a href={'mailto:'+business.email}>{business.email}</a>.</p></>:<><h3>Enquiries and confirmation</h3><p>An enquiry is not a confirmed booking. Availability, pricing, payment arrangements, cancellations and any applicable charges must be agreed directly with the business before you book.</p><h3>Your itinerary</h3><p>Routes and stops depend on available time, weather, local conditions and attraction access. Admission fees and inclusions will be confirmed with your quote. Cruise passengers should share arrival and departure times so return-to-port plans can be discussed.</p><h3>Travel requirements</h3><p>Please disclose party size, luggage, child-seat and accessibility needs before confirming a journey. Vehicle capacity and arrangements are confirmed directly. Promotional illustrations may differ from actual scenery and vehicles.</p></>}<Link className="text-link" to="/contact">Contact the team <ArrowUpRight size={18}/></Link></section>}
