import Scene from '../components/Scene';
import {Link} from 'react-router-dom';
import {ArrowUpRight,Check} from 'lucide-react';
import {PageHero,Title,Button,CTA,LocationBlock,TrustStrip,Breadcrumbs} from '../components/Shared';
import {business} from '../data/business';
import {GA_ID} from '../lib/analytics';
import Booking from './Booking';
export function About(){return <><PageHero eyebrow="ABOUT US" title={'About '+business.name} text="A local tour and transportation business in Sydney, Nova Scotia, helping visitors see Cape Breton Island at their own pace." crumbs={[['About']]}/><section className="wrap section about-story"><div><Title eyebrow="WHO WE ARE">An island best seen<br/><em>at your own pace.</em></Title><p className="lead">Some of the best moments happen between destinations. A bend in the road. A harbour in the evening light. A view that makes you ask for one more stop.</p><p>We help visitors experience Cape Breton through personalised private tours and comfortable transportation. From a simple airport pickup to a carefully planned day on the Cabot Trail, our approach starts with listening to what you need.</p><p>Based in Sydney, Nova Scotia, we bring tours and everyday travel together. You plan directly with us, ask questions and shape a journey that fits your time on the island.</p><Button to="/contact/">Let’s get to know your plans</Button></div><figure><Scene name="harbour"/><figcaption>Maritime travel inspiration · supplied illustration</figcaption></figure></section><TrustStrip/>
<section className="wrap section about-details"><div><h2>Where we operate</h2><p>We’re based at {business.street} in Sydney and operate across Cape Breton Island: around Sydney and its cruise terminal and airport, and out to Louisbourg, the Bras d’Or Lake, Baddeck, Iona and the Cabot Trail.</p><p className="inline-links"><Link to="/destinations/">Our destinations</Link></p></div><div><h2>What we offer</h2><ul className="check-list">{[['Private Cape Breton tours','/cape-breton-tours/'],['Cruise shore excursions from Sydney','/sydney-cruise-port-tours/'],['Taxi and private transportation','/taxi-sydney-nova-scotia/'],['Sydney airport transfers','/airport-transfers-sydney-ns/']].map(([label,to])=><li key={to}><Check size={18}/><Link to={to}>{label}</Link></li>)}</ul></div><div><h2>Why Cape Breton</h2><p>Cape Breton rewards visitors who slow down. The island’s scenery, history and music are best experienced with time to stop, talk and look around, so we would rather show you a few places well than rush you past many.</p></div></section>
<section className="wrap section"><h2 className="values-heading">Our approach to private tours</h2><div className="values-grid">{[['Your plans first','A good journey starts with a conversation. Your interests, pace and practical needs guide the plan.'],['Comfort & hospitality','From the first enquiry to the day you travel, we aim to make the arrangements clear and personal.'],['Honest timing','We plan realistic routes, especially for cruise passengers, and tell you when a plan is too ambitious.']].map(([t,p])=><div key={t}><h3>{t}</h3><p>{p}</p></div>)}</div></section><CTA/></>}
export function Contact(){return <><PageHero eyebrow="CONTACT US" title={'Contact '+business.name} text="Call, email or WhatsApp our team in Sydney, Nova Scotia, or send your trip details below. We’d love to hear from you." crumbs={[['Contact']]}/><LocationBlock/><Booking embedded/></>}
export function Legal({privacy=false}){return <section className="wrap section legal"><Breadcrumbs items={[[privacy?'Privacy policy':'Booking information']]}/><Title as="h1" eyebrow="HELPFUL INFORMATION">{privacy?'Privacy & your enquiry':'Before you book'}</Title>{privacy?<><h2>What you share</h2><p>The enquiry forms use the details you enter to prepare a message. This website does not submit your enquiry to a booking database. When you choose WhatsApp or email, you send your details through that service.</p><h2>Third-party services</h2><p>Google Maps, Google Fonts, WhatsApp and your email provider may process information under their own privacy policies. Saved tours are stored only in your browser so you can revisit your wish list.</p><h2>Analytics</h2><p>{GA_ID?'This website uses Google Analytics to understand how visitors use the site, for example which pages are viewed and when contact links are used. Google Analytics uses cookies; you can block them in your browser settings or with Google’s opt-out add-on.':'This website does not use advertising or analytics cookies.'}</p><h2>Contact us</h2><p>For questions about information you send to the business, email <a href={'mailto:'+business.email}>{business.email}</a>.</p></>:<><h2>Enquiries and confirmation</h2><p>An enquiry is not a confirmed booking. Availability, pricing, payment arrangements, cancellations and any applicable charges must be agreed directly with the business before you book.</p><h2>Your itinerary</h2><p>Routes and stops depend on available time, weather, local conditions and attraction access. Admission fees and inclusions will be confirmed with your quote. Cruise passengers should share arrival and all-aboard times so return-to-ship plans can be discussed.</p><h2>Travel requirements</h2><p>Please disclose party size, luggage, child-seat and accessibility needs before confirming a journey. Vehicle capacity and arrangements are confirmed directly. Promotional illustrations may differ from actual scenery and vehicles.</p></>}<Link className="text-link" to="/contact/">Contact the team <ArrowUpRight size={18}/></Link></section>}
export function NotFound(){return <section className="wrap section not-found"><p className="eyebrow">PAGE NOT FOUND</p><h1>That road doesn’t lead anywhere.</h1><p>The page may have moved. Try one of these instead:</p><ul className="check-list">{[['Cape Breton tours','/cape-breton-tours/'],['Cabot Trail tours','/cabot-trail-tours/'],['Sydney cruise port tours','/sydney-cruise-port-tours/'],['Taxi & transfers','/taxi-sydney-nova-scotia/'],['Contact us','/contact/']].map(([label,to])=><li key={to}><Check size={18}/><Link to={to}>{label}</Link></li>)}</ul><Button to="/">Return home</Button></section>}
