import {useEffect,useRef,useState} from 'react';
import {Link,useLocation,useNavigate} from 'react-router-dom';
import {Heart,Menu,X,Search,Phone} from 'lucide-react';
import useSavedTours from '../hooks/useSavedTours';
import {brandDescriptor,brandMark,business} from '../data/business';
import {tours} from '../data/tours';
export const navigation=[['Tours','/cape-breton-tours/'],['Destinations','/destinations/'],['Cruise excursions','/sydney-cruise-port-tours/'],['Taxi & transfers','/taxi-sydney-nova-scotia/'],['Travel guides','/guides/'],['About','/about/'],['Contact','/contact/']];
// Tour pages count as "Tours" for the active navigation state.
const isActive=(path,pathname)=>pathname.startsWith(path)||(path==='/cape-breton-tours/'&&tours.some(t=>t.path===pathname));
export default function Header(){const [menu,setMenu]=useState(false);const {saved}=useSavedTours();const location=useLocation();const navigate=useNavigate();const ref=useRef(null);useEffect(()=>{setMenu(false)},[location]);useEffect(()=>{document.body.style.overflow=menu?'hidden':'';function key(e){if(e.key==='Escape'){setMenu(false);ref.current?.querySelector('.menu-toggle')?.focus()}if(menu&&e.key==='Tab'){const nodes=[...ref.current.querySelectorAll('.menu-toggle,.mobile-menu a')];const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}document.addEventListener('keydown',key);return()=>{document.body.style.overflow='';document.removeEventListener('keydown',key)}},[menu]);const book=tours.find(t=>t.path===location.pathname);return <><header className="market-header" ref={ref}><div className="wrap market-header-inner"><Link className="market-brand" to="/" aria-label={business.name + ' — home'}><img className="brand-logo" src={business.logo} width="48" height="48" alt="" decoding="async"/><span className="market-brand-text"><span className="market-brand-name">{brandMark}</span><small className="market-brand-tagline">{brandDescriptor}</small></span></Link><form className="header-search" role="search" onSubmit={e=>{e.preventDefault();navigate('/cape-breton-tours/?q='+encodeURIComponent(new FormData(e.currentTarget).get('q')))}}><Search size={18}/><input name="q" aria-label="Search tours" placeholder="Find your next adventure"/><button aria-label="Search">Go</button></form><nav aria-label="Quick links"><Link to="/cape-breton-tours/?saved=1" className="saved-nav" aria-label={'Saved tours'+(saved.length?' ('+saved.length+')':'')}><Heart size={19}/>Saved{saved.length>0&&<span>{saved.length}</span>}</Link><a className="header-phone" href={'tel:'+business.tel}><Phone size={17}/>{business.phone}</a></nav><Link className="button navy header-cta" to={book?'/book/?tour='+book.slug:'/book/'}>Book a tour</Link><button className="menu-toggle" aria-label={menu?'Close menu':'Open menu'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button>{menu&&<div className="mobile-menu"><nav aria-label="Mobile navigation">{[...navigation,['Saved tours','/cape-breton-tours/?saved=1'],['Book a tour','/book/']].map(([label,url])=><Link key={url} to={url} aria-current={isActive(url,location.pathname)&&!url.includes('?')?'page':undefined}>{label}</Link>)}</nav><a href={'tel:'+business.tel}><Phone size={17}/> {business.phone}</a></div>}</div></header><nav className="market-subnav" aria-label="Main navigation"><div className="wrap">{navigation.map(([label,url])=><Link key={url} to={url} className={isActive(url,location.pathname)?'active':undefined} aria-current={isActive(url,location.pathname)?'page':undefined}>{label}</Link>)}</div></nav></>}
