import useSavedTours from '../hooks/useSavedTours';
import {Heart,Clock3} from 'lucide-react';
import Scene from './Scene';
import {Link,useSearchParams} from 'react-router-dom';
import {ArrowUpRight,Compass,Car,MapPin,MessageCircle,Phone,Plane,Ship,Building2,Route,Users,Camera,Check} from 'lucide-react';
import {business,whatsapp,maps,reviewUrl,tours} from '../data/tours';
export function Button({to,children='Plan your journey',variant='navy'}){return <Link className={'button '+variant} to={to||'/book'}>{children}</Link>}
export function Title({eyebrow,children,text,as:Heading="h2"}){return <div className="section-title"><p className="eyebrow">{eyebrow}</p><Heading>{children}</Heading>{text&&<p>{text}</p>}</div>}
export function PageHero({eyebrow,title,text,image='coast'}){return <section className="page-hero"><Scene name={image}/><div className="wrap"><p className="eyebrow light">{eyebrow}</p><h1>{title}</h1>{text&&<p>{text}</p>}</div><span className="image-note">Scenic illustration</span></section>}
export function TourCard({tour}){const [params]=useSearchParams();const href='/tours/'+tour.slug+(params.get('date')?'?date='+encodeURIComponent(params.get('date')):'');const {saved,toggle}=useSavedTours();const selected=saved.includes(tour.slug);return <article className="tour-card"><div className="tour-image-wrap"><Link to={href} className="tour-image"><Scene name={tour.image} label={tour.title+' — scenic illustration'}/><span className="image-note">Illustration</span></Link><button className={'save-tour '+(selected?'is-saved':'')} aria-label={(selected?'Unsave ':'Save ')+tour.title} aria-pressed={selected} onClick={()=>toggle(tour.slug)}><Heart size={20} fill={selected?'currentColor':'none'}/></button><span className="tag">Private experience</span></div><div className="tour-card-body"><p className="card-location"><MapPin size={13}/> Cape Breton Island, Nova Scotia</p><h3><Link to={href}>{tour.title}</Link></h3><p className="card-category">{tour.category}</p><p className="card-description">{tour.description}</p><div className="card-facts"><span><Clock3 size={15}/> Flexible itinerary</span><span><Check size={15}/> Pickup by arrangement</span></div><div className="card-bottom"><div><strong>Request a quote</strong><small>Personalised for your group</small></div><Link aria-label={'Explore '+tour.title} to={href}>View tour</Link></div></div></article>}
export function TrustStrip(){return <div className="trust wrap">{[[Compass,'A local perspective','An island worth getting to know.'],[Car,'Comfort comes along','Relax and enjoy the road.'],[MapPin,'Made around you','Your interests. Your own pace.'],[MessageCircle,'A conversation away','Easy, personal trip planning.']].map(([Icon,title,copy])=><div key={title}><Icon size={29} strokeWidth={1.3}/><span><strong>{title}</strong><small>{copy}</small></span></div>)}</div>}
export const services=[[Plane,'Airport transfers','Arrange a pickup around your flight details.'],[Ship,'Cruise port pickup','Make the most of your time ashore.'],[Building2,'Hotel transportation','From your stay to your next stop.'],[Car,'Local taxi service','A comfortable way to get around.'],[Route,'Long-distance rides','Discuss your route and timing with us.'],[Users,'Private transportation','Share your group size and travel plans.'],[Camera,'Tour transportation','Connect the places on your wish list.'],[Compass,'Custom transfers','A journey arranged around your needs.']];
export function Services({all=false}){return <div className="service-grid">{services.slice(0,all?8:4).map(([Icon,title,copy])=><Link to={'/book?service='+encodeURIComponent(title)} key={title}><Icon size={30} strokeWidth={1.3}/><h3>{title}</h3><p>{copy}</p><ArrowUpRight size={20}/></Link>)}</div>}
export function CTA(){return <section className="cta"><div className="wrap"><p className="eyebrow light">LET’S MAKE A DAY OF IT</p><h2>Your next great memory<br/>starts with <em>a hello.</em></h2><Button variant="gold">Plan your Cape Breton journey</Button></div></section>}
export function LocationBlock(){return <section className="location wrap section"><div><Title eyebrow="A WARM WELCOME IN SYDNEY">Find us in<br/><em>Cape Breton.</em></Title><p>{business.address}</p><a className="contact-phone" href="tel:+19025494542">{business.phone}</a><a className="contact-email" href={'mailto:'+business.email}>{business.email}</a><a className="text-link" href={maps} target="_blank" rel="noreferrer">Get directions <ArrowUpRight size={18}/></a></div><iframe title="Map of 193 Henry Street, Sydney, Nova Scotia" src={'https://maps.google.com/maps?q='+encodeURIComponent(business.address)+'&z=14&output=embed'} loading="lazy" referrerPolicy="no-referrer-when-downgrade"/></section>}
export function Reviews(){return <section className="reviews wrap section"><div><p className="eyebrow">FROM OUR TRAVELLERS</p><h2>Good journeys.<br/><em>Real stories.</em></h2></div><div><p>See what travellers have shared about their experience with New Scotland Coastal and Cape Breton Tours.</p><a className="text-link" href={reviewUrl} target="_blank" rel="noreferrer">Read our Google reviews <ArrowUpRight size={18}/></a></div></section>}
export function Footer(){return <><footer><div className="wrap footer-grid"><div><Link to="/"><img className="footer-logo" src="/images/logo.webp" alt={business.name}/></Link><p>Scenic roads. Local connections.<br/>A little more Cape Breton.</p></div><div><h4>Explore</h4>{[['Our story','/about'],['Our tours','/tours'],['Taxi & transfers','/taxi-service'],['Gallery','/gallery'],['Contact','/contact']].map(([s,p])=><Link key={p} to={p}>{s}</Link>)}</div><div><h4>Your next adventure</h4>{tours.slice(0,4).map(t=><Link key={t.slug} to={'/tours/'+t.slug}>{t.title}</Link>)}<Link to="/tours/private-tour">Private journeys</Link></div><div><h4>Let’s talk</h4><a href="tel:+19025494542">{business.phone}</a><a href={'mailto:'+business.email}>{business.email}</a><p>{business.address}</p><a href={whatsapp()} target="_blank" rel="noreferrer">Chat on WhatsApp</a></div></div><div className="wrap footer-bottom"><span>© {new Date().getFullYear()} {business.name}</span><div><Link to="/privacy">Privacy</Link><Link to="/terms">Booking information</Link></div></div></footer><a className="floating-chat" href={whatsapp()} target="_blank" rel="noreferrer" aria-label="Enquire on WhatsApp"><MessageCircle/></a><div className="mobile-actions"><a href="tel:+19025494542"><Phone size={18}/>Call</a><a href={whatsapp()} target="_blank" rel="noreferrer"><MessageCircle size={18}/>WhatsApp</a><Link to="/book"><Compass size={18}/>Book a tour</Link></div></>}
