import {rateLabel} from '../data/pricing';
import useSavedTours from '../hooks/useSavedTours';
import {useEffect,useState} from 'react';
import {Heart,Clock3,Star,ArrowUp,Facebook,Instagram,ExternalLink,MessageSquareText} from 'lucide-react';
import Scene from './Scene';
import {Link,useLocation,useSearchParams} from 'react-router-dom';
import {ArrowUpRight,Compass,Car,MapPin,MessageCircle,Phone,Plane,Ship,Building2,Route,Users,Camera,Check} from 'lucide-react';
import {business,profiles,whatsapp,tourWhatsapp,sms,tourSms,directions,reviewUrl,withUtm} from '../data/business';
import {tours,tourBySlug} from '../data/tours';
import {destinations} from '../data/destinations';
import {guides} from '../data/guides';
import {reviews} from '../data/reviews';
export function Button({to,children='Plan your journey',variant='navy'}){return <Link className={'button '+variant} to={to||'/book/'}>{children}</Link>}
export function SmartLink({to,children,className}){return /^https?:/.test(to)?<a className={className} href={to} target="_blank" rel="noopener noreferrer">{children}<ExternalLink size={13} aria-hidden="true"/></a>:<Link className={className} to={to}>{children}</Link>}
export function Title({eyebrow,children,text,as:Heading="h2"}){return <div className="section-title"><p className="eyebrow">{eyebrow}</p><Heading>{children}</Heading>{text&&<p>{text}</p>}</div>}
export function Breadcrumbs({items}){return <nav className="breadcrumbs" aria-label="Breadcrumb"><Link to="/">Home</Link>{items.map(([name,path],i)=><span key={name} className="crumb"><span aria-hidden="true">/</span>{path&&i<items.length-1?<Link to={path}>{name}</Link>:<span aria-current="page">{name}</span>}</span>)}</nav>}
export function PageHero({eyebrow,title,text,image='coast',crumbs,children}){return <section className="page-hero"><Scene name={image} decorative priority sizes="100vw"/><div className="wrap">{crumbs&&<Breadcrumbs items={crumbs}/>}<p className="eyebrow light">{eyebrow}</p><h1>{title}</h1>{text&&<p>{text}</p>}{children}</div></section>}
export function TourCard({tour}){const [params]=useSearchParams();const href=tour.path+(params.get('date')?'?date='+encodeURIComponent(params.get('date')):'');const {saved,toggle}=useSavedTours();const selected=saved.includes(tour.slug);return <article className="tour-card"><div className="tour-image-wrap"><Link to={href} className="tour-image" tabIndex={-1} aria-hidden="true"><Scene name={tour.image} sizes="(max-width: 760px) 50vw, 25vw" decorative/><span className="image-note">Illustration</span></Link><button className={'save-tour '+(selected?'is-saved':'')} aria-label={(selected?'Unsave ':'Save ')+tour.title} aria-pressed={selected} onClick={()=>toggle(tour.slug)}><Heart size={20} fill={selected?'currentColor':'none'}/></button><span className="tag">Private experience</span></div><div className="tour-card-body"><p className="card-location"><MapPin size={13}/> Cape Breton Island, Nova Scotia</p><h3><Link to={href}>{tour.title}</Link></h3><p className="card-category">{tour.category}</p><p className="card-description">{tour.description}</p><div className="card-facts"><span><Clock3 size={15}/> Flexible itinerary</span><span><Check size={15}/> Pickup by arrangement</span></div><div className="card-bottom"><div><strong>{rateLabel(tour.slug)}</strong><small>CAD · Final quote confirmed before booking</small></div><Link aria-label={'View tour: '+tour.name} to={href}>View tour</Link></div></div></article>}
export function TrustStrip(){return <div className="trust wrap">{[[Compass,'A local perspective','An island worth getting to know.'],[Car,'Comfort comes along','Relax and enjoy the road.'],[MapPin,'Made around you','Your interests. Your own pace.'],[MessageCircle,'A conversation away','Easy, personal trip planning.']].map(([Icon,title,copy])=><div key={title}><Icon size={29} strokeWidth={1.3}/><span><strong>{title}</strong><small>{copy}</small></span></div>)}</div>}
export const services=[[Plane,'Airport transfers','Arrange a pickup around your flight details.','/airport-transfers-sydney-ns/'],[Ship,'Cruise port pickup','Make the most of your time ashore.','/sydney-cruise-port-tours/'],[Building2,'Hotel transportation','From your stay to your next stop.'],[Car,'Local taxi service','A comfortable way to get around.'],[Route,'Long-distance rides','Discuss your route and timing with us.'],[Users,'Private transportation','Share your group size and travel plans.'],[Camera,'Tour transportation','Connect the places on your wish list.','/cape-breton-tours/'],[Compass,'Custom transfers','A journey arranged around your needs.']];
export function Services({all=false}){return <div className="service-grid">{services.slice(0,all?8:4).map(([Icon,title,copy,path])=><Link to={path||'/book/?service='+encodeURIComponent(title)} key={title}><Icon size={30} strokeWidth={1.3}/><h3>{title}</h3><p>{copy}</p><ArrowUpRight size={20}/></Link>)}</div>}
export function CTA(){return <section className="cta"><div className="wrap"><p className="eyebrow light">LET’S MAKE A DAY OF IT</p><h2>Your next great memory<br/>starts with <em>a hello.</em></h2><Button variant="gold">Plan your Cape Breton journey</Button></div></section>}
export function LocationBlock(){return <section className="location wrap section"><div><Title eyebrow="A WARM WELCOME IN SYDNEY">Find us in<br/><em>Cape Breton.</em></Title><address className="nap"><strong>{business.name}</strong><span>{business.street}</span><span>{business.city}, {business.region} {business.postalCode}</span><span>{business.country}</span></address><a className="contact-phone" href={'tel:'+business.tel}>{business.phone}</a><a className="contact-email" href={'mailto:'+business.email}>{business.email}</a><div className="contact-links"><a className="text-link" href={whatsapp()} target="_blank" rel="noopener noreferrer">Chat on WhatsApp</a><a className="text-link" href={sms()}>Send a text</a><a className="text-link" href={directions} target="_blank" rel="noopener noreferrer">Get directions <ArrowUpRight size={18}/></a><a className="text-link" href={reviewUrl} target="_blank" rel="noopener noreferrer">Google reviews</a></div></div><iframe title="Map of 193 Henry Street, Sydney, Nova Scotia" src={'https://maps.google.com/maps?q='+encodeURIComponent(business.address)+'&z=14&output=embed'} loading="lazy" referrerPolicy="no-referrer-when-downgrade"/></section>}
export function ContactCard({title='Talk to a local',text='Questions about routes, timing or pickup? Plan directly with our Sydney-based team.'}){return <aside className="reservation-card contact-card"><span className="reservation-badge">Sydney, Nova Scotia</span><h2>{title}</h2><p>{text}</p><div className="reservation-actions"><a className="button navy" href={'tel:'+business.tel}><Phone size={17}/>{business.phone}</a><a className="button outline" href={whatsapp()} target="_blank" rel="noopener noreferrer"><MessageCircle size={18}/>WhatsApp us</a><a className="button outline" href={sms()}><MessageSquareText size={18}/>Text us (SMS)</a><a className="button outline" href={'mailto:'+business.email}>Email us</a></div><address className="nap"><strong>{business.name}</strong><span>{business.street}, {business.city}</span><span>{business.region} {business.postalCode}, {business.country}</span></address><a className="text-link" href={directions} target="_blank" rel="noopener noreferrer">Get directions</a></aside>}
export function Faqs({items,title='Frequently asked questions',id='faq'}){return <section id={id} className="detail-block"><h2>{title}</h2>{items.map(([q,a])=><details className="faq" key={q}><summary>{q}</summary><p>{a}</p></details>)}</section>}
// Viator / Tripadvisor buttons. A tour's own product URL wins over the general profile; nothing renders until a URL exists.
export function PlatformLinks({tour}){const viator=withUtm(tour?.viatorUrl||profiles.viator,'viator_booking');const tripadvisor=withUtm(tour?.tripadvisorUrl||profiles.tripadvisor,'tripadvisor_reviews');if(!viator&&!tripadvisor)return null;return <div className="platform-links">{viator&&<a className="button outline" href={viator} target="_blank" rel="noopener noreferrer" data-track="viator_booking_click" data-tour={tour?.slug}>Book on Viator</a>}{tripadvisor&&<a className="button outline" href={tripadvisor} target="_blank" rel="noopener noreferrer" data-track="tripadvisor_review_click" data-tour={tour?.slug}>View reviews on Tripadvisor</a>}</div>}
export function RelatedTours({slugs,title='You might also like'}){return <section className="wrap market-section"><div className="market-heading"><h2>{title}</h2><Link to="/cape-breton-tours/">View all tours</Link></div><div className="tour-grid home-experiences">{slugs.map(tourBySlug).filter(Boolean).map(t=><TourCard key={t.slug} tour={t}/>)}</div></section>}
// Renders the content blocks used by service, destination and guide pages (see src/data/services.js).
export function ContentSections({sections}){return sections.map(s=><section className="detail-block" key={s.h2}><h2>{s.h2}</h2>{s.p?.map(p=><p key={p}>{p}</p>)}
{s.list&&<ul className="check-list">{s.list.map(item=><li key={item}><Check size={18}/>{item}</li>)}</ul>}
{s.steps&&<ol className="itinerary-stops">{s.steps.map((step,i)=><li key={step}><span>{i+1}</span><div><p>{step}</p></div></li>)}</ol>}
{s.cards&&<div className="option-cards">{s.cards.map(([title,text,links])=><div key={title}><h3>{title}</h3><p>{text}</p><p className="inline-links">{links.map(([label,to])=><SmartLink key={to} to={to}>{label}</SmartLink>)}</p></div>)}</div>}
{s.table&&<div className="table-scroll"><table className="compare-table"><thead><tr>{s.table.head.map(h=><th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{s.table.rows.map(([name,time,fit,to])=><tr key={name}><th scope="row"><Link to={to}>{name}</Link></th><td>{time}</td><td>{fit}</td></tr>)}</tbody></table></div>}
{s.numbered&&<ol className="numbered-list">{s.numbered.map(([title,text,links],i)=><li key={title}><span>{i+1}</span><div><h3>{title}</h3><p>{text}</p>{links.length>0&&<p className="inline-links">{links.map(([label,to])=><SmartLink key={to} to={to}>{label}</SmartLink>)}</p>}</div></li>)}</ol>}
{s.links&&<p className="inline-links">{s.links.map(([label,to])=><SmartLink key={to} to={to}>{label}</SmartLink>)}</p>}</section>)}
export function Confidence(){return <section className="confidence wrap" aria-labelledby="confidence-heading"><div><p className="promo-kicker">TRAVEL WITH A LOCAL OPERATOR</p><h2 id="confidence-heading">Explore Cape Breton with confidence</h2><p>{business.name} provides private sightseeing and transportation across Cape Breton Island from Sydney, Nova Scotia. You plan directly with the people who drive you.</p><ul className="confidence-list">{['Local Cape Breton operator based in Sydney','Private tours for your group only','Cruise passenger pickup by arrangement','Flexible, personalised itineraries','Prices and details confirmed before you book'].map(item=><li key={item}><Check size={17}/>{item}</li>)}</ul></div><div className="review-panel">{reviews.length>0?<div className="review-grid">{reviews.slice(0,3).map(r=><figure key={r.name+r.text}><div className="stars" aria-label={r.rating+' out of 5 stars'}>{Array.from({length:r.rating},(_,i)=><Star key={i} size={15} fill="currentColor"/>)}</div><blockquote>“{r.text}”</blockquote><figcaption>{r.name} · {r.tour}<small>Review on {r.source}</small></figcaption></figure>)}</div>:<div className="review-empty"><Star size={26}/><h3>Read what our travellers say</h3><p>Our reviews live on our Google Business Profile, where every review comes from a real customer.</p></div>}<div className="review-links"><a className="button navy" href={reviewUrl} target="_blank" rel="noopener noreferrer" data-track="google_reviews_click">Read Google reviews</a>{profiles.tripadvisor&&<a className="button outline" href={withUtm(profiles.tripadvisor,'tripadvisor_reviews')} target="_blank" rel="noopener noreferrer" data-track="tripadvisor_review_click">Tripadvisor reviews</a>}{profiles.viator&&<a className="button outline" href={withUtm(profiles.viator,'viator_booking')} target="_blank" rel="noopener noreferrer">Find us on Viator</a>}</div></div></section>}
function BackToTop(){const [show,setShow]=useState(false);useEffect(()=>{const onScroll=()=>setShow(window.scrollY>900);window.addEventListener('scroll',onScroll,{passive:true});return()=>window.removeEventListener('scroll',onScroll)},[]);return show?<button className="back-to-top" onClick={()=>window.scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})} aria-label="Back to top"><ArrowUp size={20}/></button>:null}
const socials=[[Facebook,'Facebook',profiles.facebook],[Instagram,'Instagram',profiles.instagram]].filter(s=>s[2]);
export function Footer(){const {pathname}=useLocation();const tour=tours.find(t=>t.path===pathname);const book=tour?'/book/?tour='+tour.slug:'/book/';return <><footer><div className="wrap footer-grid">
<div className="footer-brand"><Link to="/"><img className="footer-logo" src={business.logo} width="100" height="100" loading="lazy" alt={business.name+' logo'}/></Link><p><strong>{business.name}</strong><br/>Private Cape Breton tours, shore excursions and taxi service from Sydney, Nova Scotia.</p>{socials.length>0&&<div className="footer-social">{socials.map(([Icon,label,url])=><a key={label} href={url} target="_blank" rel="noopener noreferrer" aria-label={business.shortName+' on '+label}><Icon size={19}/></a>)}{profiles.tripadvisor&&<a href={profiles.tripadvisor} target="_blank" rel="noopener noreferrer">Tripadvisor</a>}{profiles.viator&&<a href={profiles.viator} target="_blank" rel="noopener noreferrer">Viator</a>}</div>}</div>
<div><h2>Popular tours</h2>{tours.slice(0,5).map(t=><Link key={t.slug} to={t.path}>{t.title}</Link>)}<Link to="/sydney-cruise-port-tours/">Cruise shore excursions</Link><Link to="/taxi-sydney-nova-scotia/">Taxi & transfers</Link></div>
<div><h2>Destinations</h2>{destinations.slice(0,6).map(d=><Link key={d.slug} to={d.path}>{d.name}</Link>)}<Link to="/destinations/">All destinations</Link></div>
<div><h2>Travel guides</h2>{guides.map(g=><Link key={g.slug} to={g.path}>{g.title.split(':')[0]}</Link>)}<Link to="/things-to-do-cape-breton/">Things to do in Cape Breton</Link><Link to="/about/">About us</Link></div>
<div><h2>Contact</h2><address><span>{business.street}</span><span>{business.city}, {business.region} {business.postalCode}</span><span>{business.country}</span></address><a href={'tel:'+business.tel}>{business.phone}</a><a href={'mailto:'+business.email}>{business.email}</a><a href={whatsapp()} target="_blank" rel="noopener noreferrer">Chat on WhatsApp</a><a href={sms()}>Send a text (SMS)</a><a href={directions} target="_blank" rel="noopener noreferrer">Get directions</a><Link to="/contact/">Contact page</Link></div>
</div><div className="wrap footer-bottom"><span className="copyright">© {new Date().getFullYear()} {business.name}. All rights reserved. <span aria-hidden="true">|</span> Developed by <a href="https://sarangrajan.in/enitexa.ai/" target="_blank" rel="noopener noreferrer">Enitexa.ai</a></span><div><Link to="/privacy/">Privacy policy</Link><Link to="/terms/">Booking information</Link><Link to="/gallery/">Gallery</Link></div></div></footer><BackToTop/><a className="floating-chat" href={whatsapp()} target="_blank" rel="noopener noreferrer" aria-label="Enquire on WhatsApp"><MessageCircle/></a><div className="mobile-actions"><a href={'tel:'+business.tel}><Phone size={18}/>Call</a><a href={tour?tourWhatsapp(tour.name):whatsapp()} target="_blank" rel="noopener noreferrer"><MessageCircle size={18}/>WhatsApp</a><a href={tour?tourSms(tour.name):sms()}><MessageSquareText size={18}/>Text</a><Link to={book} data-tour={tour?.slug}><Compass size={18}/>{tour?'Book':'Book a tour'}</Link></div></>}
