import AgentTools from './components/AgentTools';
import {useEffect} from 'react';
import {Routes,Route,useLocation,Link} from 'react-router-dom';
import Header from './components/Header';
import {Footer} from './components/Shared';
import Home from './pages/Home';
import {Tours,TourDetails} from './pages/Tours';
import Booking from './pages/Booking';
import Gallery from './pages/Gallery';
import {Taxi,About,Contact,Legal} from './pages/Other';
import {tours,business} from './data/tours';
function PageMetadata(){const {pathname}=useLocation();useEffect(()=>{window.scrollTo(0,0);const tour=tours.find(t=>pathname==='/tours/'+t.slug);const title=tour?tour.title+' Private Tour':({'/':'Cape Breton Tours & Taxi Service','/tours':'Private Cape Breton Tours','/about':'Our Story','/taxi-service':'Cape Breton Taxi & Airport Transfers','/gallery':'Cape Breton Travel Gallery','/book':'Plan Your Cape Breton Journey','/contact':'Contact Us','/privacy':'Privacy','/terms':'Booking Information'}[pathname]||'Page Not Found');document.title=title+' | New Scotland Coastal Tours';const description=tour?tour.description:'Discover Cape Breton with private scenic tours, Cabot Trail journeys and comfortable taxi transportation from Sydney, Nova Scotia.';function meta(key,value,property=false){let node=document.head.querySelector(`meta[${property?'property':'name'}="${key}"]`);if(!node){node=document.createElement('meta');node.setAttribute(property?'property':'name',key);document.head.append(node)}node.content=value}meta('description',description);meta('og:title',document.title,true);meta('og:description',description,true);meta('og:type','website',true);meta('og:url',business.website+pathname,true);meta('twitter:card','summary');meta('twitter:title',document.title);meta('twitter:description',description);let canonical=document.head.querySelector('link[rel="canonical"]');if(!canonical){canonical=document.createElement('link');canonical.rel='canonical';document.head.append(canonical)}canonical.href=business.website+pathname;let schema=document.getElementById('business-schema');if(!schema){schema=document.createElement('script');schema.type='application/ld+json';schema.id='business-schema';document.head.append(schema)}schema.textContent=JSON.stringify({'@context':'https://schema.org','@graph':[{'@type':'LocalBusiness','@id':business.website+'/#business',name:business.name,url:business.website,telephone:business.phone,email:business.email,address:{'@type':'PostalAddress',streetAddress:'193 Henry St',addressLocality:'Sydney',addressRegion:'NS',postalCode:'B1N 2H4',addressCountry:'CA'},areaServed:'Cape Breton Island'},...(tour?[{'@type':'TouristTrip',name:tour.title,description:tour.description,url:business.website+pathname,provider:{'@id':business.website+'/#business'}},{'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:business.website},{'@type':'ListItem',position:2,name:'Tours',item:business.website+'/tours'},{'@type':'ListItem',position:3,name:tour.title,item:business.website+pathname}]}]:[])]});},[pathname]);return null}
export default function App(){return <><a className="skip-link" href="#main">Skip to content</a><PageMetadata/><AgentTools/><Header/><main id="main"><Routes><Route path="/" element={<Home/>}/><Route path="/tours" element={<Tours/>}/><Route path="/tours/:slug" element={<TourDetails/>}/><Route path="/about" element={<About/>}/><Route path="/taxi-service" element={<Taxi/>}/><Route path="/gallery" element={<Gallery/>}/><Route path="/book" element={<Booking/>}/><Route path="/contact" element={<Contact/>}/><Route path="/privacy" element={<Legal privacy/>}/><Route path="/terms" element={<Legal/>}/><Route path="*" element={<section className="wrap section"><h1>That road doesn’t lead anywhere.</h1><Link className="button navy" to="/">Return home</Link></section>}/></Routes></main><Footer/></>}
