import React from 'react';
import {createRoot,hydrateRoot} from 'react-dom/client';
import {BrowserRouter} from 'react-router-dom';
import App from './App';
import './style.css';
import './marketplace.css';
import './content.css';
import './season-theme.css';
const root=document.getElementById('root');
const app=<BrowserRouter><App/></BrowserRouter>;
if(root.hasChildNodes())hydrateRoot(root,app);else createRoot(root).render(app);
